// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEgGFznnqBx3h43qACKmc4vRn-PleSeVM',
    appId: '1:768557846321:web:2e9fb2af653038b053ea10',
    messagingSenderId: '768557846321',
    projectId: 'app-abastecimento-4a1fa',
    authDomain: 'app-abastecimento-4a1fa.firebaseapp.com',
    storageBucket: 'app-abastecimento-4a1fa.firebasestorage.app',
    measurementId: 'G-CJ6EB66JD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQocVX0r8GMeX6nAH79f_LXrTn0h3L5pg',
    appId: '1:768557846321:android:82d93861a97ea9af53ea10',
    messagingSenderId: '768557846321',
    projectId: 'app-abastecimento-4a1fa',
    storageBucket: 'app-abastecimento-4a1fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5e04phrSK6aAg3lPcAHLsVV-hQNNulig',
    appId: '1:768557846321:ios:bde46cc2c2399c4b53ea10',
    messagingSenderId: '768557846321',
    projectId: 'app-abastecimento-4a1fa',
    storageBucket: 'app-abastecimento-4a1fa.firebasestorage.app',
    iosBundleId: 'com.example.appAbastecimento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5e04phrSK6aAg3lPcAHLsVV-hQNNulig',
    appId: '1:768557846321:ios:bde46cc2c2399c4b53ea10',
    messagingSenderId: '768557846321',
    projectId: 'app-abastecimento-4a1fa',
    storageBucket: 'app-abastecimento-4a1fa.firebasestorage.app',
    iosBundleId: 'com.example.appAbastecimento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEgGFznnqBx3h43qACKmc4vRn-PleSeVM',
    appId: '1:768557846321:web:7e593fafe79db4ba53ea10',
    messagingSenderId: '768557846321',
    projectId: 'app-abastecimento-4a1fa',
    authDomain: 'app-abastecimento-4a1fa.firebaseapp.com',
    storageBucket: 'app-abastecimento-4a1fa.firebasestorage.app',
    measurementId: 'G-V01QJFB50G',
  );
}
